server:
  port: 8080

spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comm
    username: postgres
    password: 12345



  springfox:
    documentation:
      swagger:
        v2:
          use-model-v3: true



jwt:
  token:
    expired: 3600000
    secret: jwtappdemo


